### ISSUE TITLE
[BUG] Wac advanced spawn check issues.

### ISSUE THREAD

**Issue by ickycoolboy** [00875/dpp#1]
This is an amazing addon just to say that right now...

Anyway two "bugs" I have seen with this option enabled.

1. Some wac helicopter rotor blades are frozen still.
2. People can still spam spawning helicopters.

If you need any more info please ask.

**Comment by bgpony** [comment]
Thank you for your help.

**Comment by 00875** [comment]
Did you tried physgun reload? For me it works
![20160416120844_1](https://cloud.githubusercontent.com/assets/6339511/14579233/7806aa2a-03cb-11e6-8d2f-7e62e9ea2c3c.jpg)
![20160416120845_1](https://cloud.githubusercontent.com/assets/6339511/14579234/79e18752-03cb-11e6-9a5e-0263d4416ab5.jpg)

**Comment by 00875** [comment]
Nothing else i can do there. Sorry :c
