### ISSUE TITLE
[Request] Option for timer based antispam.

### ISSUE THREAD

**Issue by ickycoolboy** [00875/dpp#2]
Some addons like Neurotec have entities with multiple parts welded together. Typical ghost antispam causes problems such half a ship being frozen:
http://puu.sh/ojQfK/78d8f66bea.jpg

My request is perhaps make an option available to limit spawning and tool use to a second based ratio instead of ghosting. 
An example of a prop protection addonthat uses this is:
http://steamcommunity.com/sharedfiles/filedetails/?id=183047564.

So for example, with this I could set that someone could only spawn props and/or use tools every 2 seconds.

**Comment by 00875** [comment]
I'm hard to read, because i am russian. You mean that there should be Tool antispam thing? And "Antispam only for props" option?

**Comment by ickycoolboy** [comment]
That is very close, however

What I am looking for is a wait timer after spawning items and using tools. This option would be able to be changed by the user. This would prevent a player from spawning another prop or using a tool until a set amount of seconds has passed.

**Comment by 00875** [comment]
For items it is impossible, because wait timer for Props and other stuff is just same as when antispam removing entities
