### ISSUE TITLE
[Bug] Can not delete some items spawned with tools

### ISSUE THREAD

**Issue by ickycoolboy** [00875/dpp#3]
Items I have found so far include 
1. Lights
2. Balloons.

**Comment by 00875** [comment]
![20160416124207_1](https://cloud.githubusercontent.com/assets/6339511/14579351/1bc5ef46-03d0-11e6-8b9b-06d9a5bc4309.jpg)
![20160416124226_1](https://cloud.githubusercontent.com/assets/6339511/14579350/1bc5e384-03d0-11e6-9da2-1b7d68a54665.jpg)
I owned them, so i can
???

**Comment by ickycoolboy** [comment]
You are right, must be some conflict with my second server, I will do some investigations. You can close  this if you want to and I will get back with some information if I find any.
